# Generated by Django 3.2.25 on 2024-10-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='excert',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
