# Generated by Django 3.2.25 on 2024-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_blog', '0002_posts_excert'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
