# Generated by Django 3.2.25 on 2024-10-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_blog', '0005_auto_20241019_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
