# Generated by Django 3.2.25 on 2024-10-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub_blog', '0007_auto_20241024_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='post_com',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_blog.posts'),
        ),
    ]
