# Generated by Django 3.2.25 on 2024-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_blog', '0008_commentsmodel_post_com'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_upModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
